" Credit to gmarik, original: https://github.com/gmarik/dotfiles/blob/master/.vimrc

" Get this out of the way first
set nocompatible

source ~/.vim/plugins.vim

source ~/.vim/settings.vim

" Workaround for utf-8 listchars issue
if filereadable(expand("~/.vim/settings2.vim"))
  source ~/.vim/settings2.vim
endif

if has("gui_running") && filereadable(expand("~/.vim/gvimrc"))
    source ~/.vim/gvimrc
endif

if filereadable(expand("~/.vim/vimrc.local"))
  source ~/.vim/vimrc.local
endif
