#!/usr/bin/env bash

if [[ $# != '2' ]]; then
	echo "Usage: agreplace <original> <replacement>"
	return 1
fi
#ag -l $1 | xargs sed -i "s#$1#$2#g"
echo "ag -l $1 | xargs perl -pi -0777 -e \"s#${1}#${2}#g\""
echo "Changing files: $(ag -l "$1")"
ag -l "$1" | xargs perl -pi -0777 -e "s#${1}#${2}#g"
