#!/bin/bash

# This hook exists to stop me from accidentally push (or worse, force-pushing)
# to "protected" branches.

set -euo pipefail

# REMOTE_NAME="$1"
REMOTE_URL="$2"
CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

PROTECTED_BRANCHES="^(master.*|dev)$"

OTHER_REPOS=${GIT_BRANCH_PUSH_EXCLUDED_REPO_PATTERNS:-some/repo}
EXCLUDED_REPOS="^.+:(benwh/dotfiles|${OTHER_REPOS})"
EXCLUDED_USERS="^dokku@.+"

if [[ "$CURRENT_BRANCH" =~ $PROTECTED_BRANCHES ]] && \
	[[ ! "$REMOTE_URL" =~ $EXCLUDED_REPOS ]] && \
	[[ ! "$REMOTE_URL" =~ $EXCLUDED_USERS ]]; then
  read -p "Do you really want to push to \"$CURRENT_BRANCH\" for \"$REMOTE_URL\"? (y/n): " -n 1 -r < /dev/tty
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    exit 0
  fi
  echo "Push aborted."
  exit 1
fi
